civicrm-upgrade-test:
 * Allow "@4.4" notation (to run tests from all versions through 4.4)
 * Accept argument "--db-args" to pass-through MySQL details

diff --git a/civicrm-upgrade-test b/civicrm-upgrade-test
--- a/civicrm-upgrade-test
+++ b/civicrm-upgrade-test
@@ -21,6 +21,7 @@ function abspath {
 function showHelp {
       echo "Usage: $0 [--out /path/to/output/dir] [--web /path/to/web/root] [--db mysql_database_name] [--junit-xml /path/to/junit.xml] <file1.sql.bz2> <file2.sql.bz2> ..."
       echo
+      echo "(Note: To run all tests up-through version X, use @, e.g.: $0 @4.4)"
       echo "(Note: Settings may be loaded from $SCRIPT_CFG)"
 }
 
@@ -34,8 +35,8 @@ function usageError {
 
 ## Drop all tables, views, etc
 function drop_civicrm_sql {
-  DBNAME="$1"
-  MYSQLCMD="mysql $DBNAME"
+  DBNAME="$TEST_DATABASE"
+  MYSQLCMD="mysql $TEST_DATABASE_ARGS"
 
   echo; echo "Dropping civicrm_* views from database $DBNAME"
   echo "SELECT table_name FROM information_schema.TABLES  WHERE TABLE_SCHEMA='${DBNAME}' AND TABLE_TYPE = 'VIEW'" \
@@ -100,6 +101,10 @@ while [ -n "$1" ]; do
       TEST_DATABASE="$2"
       shift 2
       ;;
+    --db-args)
+      TEST_DATABASE_ARGS="$2"
+      shift 2
+      ;;
     --junit-xml)
       JUNIT_XML="$2"
       shift 2
@@ -109,7 +114,17 @@ while [ -n "$1" ]; do
       exit 1
       ;;
     *)
-      DATABASE_FILES="$DATABASE_FILES $1"
+      if [ "${1:0:1}" == "@" ]; then
+        case "$1" in
+          @4.3|@4.3.*)  DATABASE_FILES="$DATABASE_FILES 4.2* 4.3*" ;;
+          @4.4|@4.4.*)  DATABASE_FILES="$DATABASE_FILES 4.2* 4.3* 4.4*" ;;
+          @4.5|@4.5.*)  DATABASE_FILES="$DATABASE_FILES 4.2* 4.3* 4.4*" ;; ## FIXME: 4.5*
+          @master)  DATABASE_FILES="$DATABASE_FILES 4.2* 4.3* 4.4*" ;; ## FIXME: 4.5*
+          *)      echo "UpgradeTest failed: Unrecognized version ($CIVIVER)" ; exit 1; ;;
+        esac
+      else
+        DATABASE_FILES="$DATABASE_FILES $1"
+      fi
       shift
       ;;
   esac
@@ -138,6 +153,9 @@ fi
 if [ -z "$TEST_DATABASE" ]; then
   usageError "Missing or invalid database name"
 fi
+if [ -z "$TEST_DATABASE_ARGS" ]; then
+  TEST_DATABASE_ARGS="$TEST_DATABASE"
+fi
 if [ -z "$DATABASE_FILES" ]; then
   usageError "Missing list of database backup files (*.sql.bz2)"
 fi
@@ -165,19 +183,21 @@ for SQLBZ2 in $DATABASE_FILES ; do
   echo "Input [$SQLBZ2]"
   echo "Output [$OUTPUT] [$LOG]"
 
-  drop_civicrm_sql $TEST_DATABASE
+  drop_civicrm_sql
+  echo; echo "Loading database $TEST_DATABASE"
   if [[ "$SQLBZ2" == *sql.bz2 ]]; then
-    bzip2 -d -c "$SQLBZ2" | mysql "$TEST_DATABASE"
+    bzip2 -d -c "$SQLBZ2" | mysql $TEST_DATABASE_ARGS
   elif [[ "$SQLBZ2" == *sql.gz ]]; then
-    gzip -d -c "$SQLBZ2" | mysql "$TEST_DATABASE"
+    gzip -d -c "$SQLBZ2" | mysql $TEST_DATABASE_ARGS
   elif [[ "$SQLBZ2" == *sql ]]; then
-    mysql "$TEST_DATABASE" < "$SQLBZ2"
+    mysql $TEST_DATABASE_ARGS < "$SQLBZ2"
   else
     echo "Unrecognized file extension [$SQLBZ2]"
     exit 2
   fi
   pushd "$WEB_ROOT" > /dev/null
   rm -f $LOGPAT
+  echo; echo "Upgrading database $TEST_DATABASE"
   $DRUSH civicrm-upgrade-db > "$OUTPUT" 2>&1
   echo "LOGPAT: $LOGPAT" > $LOG
   cat $LOGPAT >> $LOG
